trailingComma: 'all'
tabWidth: 2
singleQuote: true
arrowParens: always
endOfLine: lf
overrides:
  - files: '*.sol'
    options:
      printWidth: 120
      tabWidth: 4
      useTabs: false
      singleQuote: false
      bracketSpacing: false
