[profile.default]
auto_detect_solc = false
solc = "0.8.20"
src = 'contracts'
out = 'out'
libs = ['lib', 'node_modules']
test = 'test'
fork_block_number = 16597500

[rpc_endpoints]
mainnet = "${ETH_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config