name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'master'

env:
  API_KEY_ALCHEMY: ${{ secrets.API_KEY_ALCHEMY }}

jobs:
  lint:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Check out the repo'
        uses: 'actions/checkout@v3'
        with:
          submodules: 'recursive'

      - name: 'Install Node.js'
        uses: 'actions/setup-node@v3'
        with:
          node-version: '18'
          cache: 'yarn'

      - name: 'Install Node.js packages'
        run: 'yarn install --frozen-lockfile'

      - name: 'Lint contracts with solhint'
        run: 'yarn lint'

      - name: 'Lint contracts with @premia/sol-linter'
        run: 'yarn sol-linter'

  build:
    needs: ['lint']
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Check out the repo'
        uses: 'actions/checkout@v3'
        with:
          submodules: 'recursive'

      - name: 'Install Node.js'
        uses: 'actions/setup-node@v3'
        with:
          node-version: '18'
          cache: 'yarn'

      - name: 'Install Node.js packages'
        run: 'yarn install --frozen-lockfile'

      - name: 'Install Foundry'
        uses: 'foundry-rs/foundry-toolchain@v1'

      - name: 'Show the Foundry config'
        run: 'forge config'

      - name: 'Build the contracts'
        run: 'forge build --sizes --deny-warnings --ignored-error-codes 3628 --ignored-error-codes 5574'

      - name: 'Cache the build so that it can be re-used by the other jobs'
        uses: 'actions/cache/save@v3'
        with:
          path: |
            out
            cache
          key: 'foundry-build-${{ github.sha }}'

  test:
    needs: ['build']
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Check out the repo'
        uses: 'actions/checkout@v3'
        with:
          submodules: 'recursive'

      - name: 'Install Node.js'
        uses: 'actions/setup-node@v3'
        with:
          node-version: '18'
          cache: 'yarn'

      - name: 'Install Node.js packages'
        run: 'yarn install --frozen-lockfile'

      - name: 'Install Foundry'
        uses: 'foundry-rs/foundry-toolchain@v1'

      - name: 'Restore the cached build'
        uses: 'actions/cache/restore@v3'
        with:
          fail-on-cache-miss: true
          key: 'foundry-build-${{ github.sha }}'
          path: |
            out
            cache

      - name: 'Run tests'
        run: 'yarn test'
