name: Run Contract Linter

on:
  workflow_dispatch:
  pull_request:

jobs:
  run-contract-linter:
    name: Contract linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install packages
        run: yarn install --non-interactive --frozen-lockfile

      - name: Run linter on all contracts
        run: find contracts -name "*.sol" | xargs yarn solhint
