name: Deploy Docs

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Build docs
        run: yarn build-docs

      - uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          cwd: './'
          files: |
            docs/book
            captain-definition
          outPath: deploy.tar

      - name: Deploy App to Caprover
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.APP_NAME }}'
          token: '${{ secrets.APP_TOKEN }}'
