name: Forge Tests

on:
  workflow_dispatch:
  pull_request:
    types: [review_requested]

env:
  FOUNDRY_PROFILE: ci
  API_KEY_ALCHEMY: ${{ secrets.API_KEY_ALCHEMY }}

jobs:
  forge-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
