name: test

on:
  workflow_dispatch:
  pull_request:
    types: [review_requested]

env:
  FOUNDRY_PROFILE: ci
  API_KEY_ALCHEMY: ${{ secrets.API_KEY_ALCHEMY }}

jobs:
  check:
    strategy:
      fail-fast: true
      matrix:
        node-version: [18.x]

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
